//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitePersonelOtomasyon.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCocukBilgisi
    {
        public int cocuk_ID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<System.DateTime> dogum_Tarihi { get; set; }
        public string okudugu_Okul { get; set; }
        public Nullable<int> personel_ID { get; set; }
    }
}
