//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitePersonelOtomasyon.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvraklar
    {
        public int evrak_ID { get; set; }
        public Nullable<bool> is_Basvuru_Formu { get; set; }
        public Nullable<bool> nufus_Cuzdan_Fotokopisi { get; set; }
        public Nullable<bool> vesikalik { get; set; }
        public Nullable<bool> ikametgah { get; set; }
        public Nullable<bool> saglik_Raporu { get; set; }
        public Nullable<bool> lisans_Basvurusu { get; set; }
        public Nullable<int> personel_ID { get; set; }
    }
}
