//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitePersonelOtomasyon.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEgitim
    {
        public int egitim_ID { get; set; }
        public string okul_Adi { get; set; }
        public string bolum { get; set; }
        public Nullable<System.DateTime> giris_Tarihi { get; set; }
        public Nullable<System.DateTime> mezuniyet_Tarihi { get; set; }
        public string ogrenim_seviyesi { get; set; }
        public Nullable<int> personel_ID { get; set; }
    }
}
