//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitePersonelOtomasyon.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIzin
    {
        public int izin_ID { get; set; }
        public string izin_Turu { get; set; }
        public string izin_Bilgisi { get; set; }
        public Nullable<System.DateTime> baslangic_Tarihi { get; set; }
        public Nullable<System.DateTime> bitis_Tarihi { get; set; }
        public Nullable<int> personel_ID { get; set; }
    }
}
