//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitePersonelOtomasyon.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanicilar
    {
        public int kullanici_ID { get; set; }
        public string kullanici_Ad { get; set; }
        public string kullanici_Sifre { get; set; }
        public Nullable<int> type_ID { get; set; }
    }
}
