//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitePersonelOtomasyon.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNufusBilgiler
    {
        public int nufus_ID { get; set; }
        public string nufusCuzdanNo { get; set; }
        public string tcKimlikNo { get; set; }
        public string babaAdi { get; set; }
        public string anaAdi { get; set; }
        public Nullable<int> nufusaKayitliOlduguIl_ID { get; set; }
        public Nullable<int> nufusaKayitliOlduguIlce_ID { get; set; }
        public string mahKoy { get; set; }
        public string ciltNo { get; set; }
        public string aileSıraNo { get; set; }
        public string sıraNo { get; set; }
        public string DogumYeri { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public Nullable<int> uyrugu_ID { get; set; }
        public Nullable<int> madeniHali_ID { get; set; }
        public string verildigiYer { get; set; }
        public Nullable<int> verilisNedeni_ID { get; set; }
        public Nullable<int> personel_ID { get; set; }
    }
}
