//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitePersonelOtomasyon.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersoneller
    {
        public int personel_ID { get; set; }
        public string personel_Ad { get; set; }
        public string personel_Soyad { get; set; }
        public string personel_Resim { get; set; }
        public Nullable<System.DateTime> personel_GirisTarihi { get; set; }
        public Nullable<int> statu_ID { get; set; }
        public Nullable<int> cinsiyet_ID { get; set; }
        public Nullable<int> fakulte_ID { get; set; }
        public Nullable<int> departman_ID { get; set; }
        public Nullable<int> unvan_ID { get; set; }
        public Nullable<int> kullanici_ID { get; set; }
    }
}
