//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitePersonelOtomasyon.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVerdigiDersler
    {
        public int ders_ID { get; set; }
        public string ders { get; set; }
        public string ders_Baslangic_Saat { get; set; }
        public string ders_Bitis_Saat { get; set; }
        public string ders_Gunu { get; set; }
        public Nullable<int> sinif_ID { get; set; }
        public Nullable<int> personel_ID { get; set; }
    }
}
